# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.
# Instructions: replace all the <placeholder> stubs in this template with values for your image.
# Some explanations come from: https://github.com/actions/starter-workflows/blob/main/automation/manual.yml

name: Push <program name> image

# This workflow should run when manually triggered by StaPH-B repo maintainer
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This job calls a workflow to build the image to the 'test' stage
  build-to-test:
    uses: SarahNadeau/docker-builds/.github/workflows/build-to-test.yml@sarah-dev  # TODO: change to reference StaPH-B if accepted in PR
    with:
      path_to_context: "./<program name>/<program version>"  # Path to directory with Dockerfile and context, e.g. "./spades/3.12.0"; if you need to have the whole repo as context (e.g. to use files in test_data), use "."
      dockerfile_name: "Dockerfile"  # Name of the Dockerfile, should be "Dockerfile"; if you need to have the whole repo as context, use e.g. "./spades/3.12.0/Dockerfile"
      cache: "<program name>"  # Use the program name as a nickname for a GitHub cache of your image's layers, e.g. "spades". The cache will speed up re-running the workflow.

  # This job calls a workflow to build the image to the 'app' stage and pushes the image to Docker Hub
  build-and-push:
    needs: build-to-test  # this jobs needs to run serially, after testing succeeds
    uses: SarahNadeau/docker-builds/.github/workflows/build-and-push.yml@sarah-dev  # TODO: change
    with:
      path_to_context: "./<program name>/<program version>"  # Same as above
      dockerfile_name: "Dockerfile"  # Same as above
      cache: "<program name>"  # Same as above
      container_name: "<program name>"  # The image name for Docker Hub, use the program name in lowercase, e.g. "spades"
      tag: "<program version>"  # The image tag for Docker Hub, use the program version, e.g. "3.12.0"
    secrets:  # These reference GitHub repository secrets to grant the GitHub action access to a Docker Hub repository to push the image to
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}  # TODO: change
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # TODO: change

  # This job calls a workflow to pull the image from Docker Hub and test that it can be run as a Singularity container
  run-singularity:
    needs: build-and-push  # test singularity run on newly pushed Docker image
    uses: SarahNadeau/docker-builds/.github/workflows/run-singularity.yml@sarah-dev  # TODO: change
    with:
      dockerhub_image: "<docker hub username>/<image name>:<image tag>"  # The image to pull, e.g. "staphb/spades:3.12.0"
