FROM ubuntu:xenial as app

ARG BLASTPLUS_VER=2.9.0

LABEL base.image="ubuntu:xenial"
LABEL software="BLAST+"
LABEL software.version=${BLASTPLUS_VER}
LABEL description="BLAST+: A suite of command-line tools to run BLAST (Basic Local Alignment Search Tool)."
LABEL website="https://www.ncbi.nlm.nih.gov/books/NBK279690/"
LABEL license.url="https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/scripts/projects/blast/LICENSE"

# Install blast+ dependencies (for running e.g. update_blastdb.pl)
RUN apt-get update && apt-get install -y \
    curl \
    libjson-perl \
    perl \
    wget

# Install blast+
RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/$BLASTPLUS_VER/ncbi-blast-$BLASTPLUS_VER+-x64-linux.tar.gz \
    && tar xvf ncbi-blast-$BLASTPLUS_VER+-x64-linux.tar.gz \
    && rm ncbi-blast-$BLASTPLUS_VER+-x64-linux.tar.gz \
    && mv ncbi-blast-$BLASTPLUS_VER+/bin/* /usr/local/bin/

RUN mkdir /data/
WORKDIR /data

FROM app as test

# Get test dependencies
RUN apt-get update && apt-get install -y python3
COPY "ncbi-blast-plus"/2.9.0/tests /tests
RUN mkdir -p /test_data/ssu
COPY test_data/ssu/16S.SRR5481494_sub.fna /test_data/ssu/

# Download blast database
RUN bash /tests/scripts/download_db.sh

# Run positive control
RUN bash /tests/scripts/run_positive_control.sh

# Check output
RUN python3 -m unittest discover -s /tests
