# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.

name: Deploy Mask Recombination image

on: workflow_dispatch

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "./mask_recombination/1.0"
      dockerfile_name: "Dockerfile"
      cache: "mask-recombination"

  build-to-deploy:
    needs: build-to-test
    uses: ./.github/workflows/build-to-deploy.yml
    with:
      path_to_context: "./mask_recombination/1.0"
      dockerfile_name: "Dockerfile"
      cache: "mask-recombination"
      container_name: "mask-recombination"
      tag: "1.0"
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  run-singularity:
    needs: build-to-deploy
    uses: ./.github/workflows/run-singularity.yml
    with:
      dockerhub_image: "snads/mask-recombination:1.0"
