name: Deploy SWGA image

on: workflow_dispatch

jobs:

  # This job calls a workflow to build the image to the 'test' stage
  build-to-test:
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./swga/0.4.4/"
      dockerfile_name: "Dockerfile"
      cache: "swga"

  # This job calls a workflow to build the image to the 'app' stage and pushes the image to Docker Hub
  build-to-deploy:
    needs: build-to-test
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    with:
      path_to_context: "./swga/0.4.4/"
      dockerfile_name: "Dockerfile"
      cache: "swga"
      container_name: "swga"
      tag: "0.4.4"
      repository_name: "snads"
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # This job calls a workflow to pull the image from Docker Hub and test that it can be run as a Singularity container
  run-singularity:
    needs: build-to-deploy
    uses: StaPH-B/docker-builds/.github/workflows/run-singularity.yml@master
    with:
      repository_name: "snads"  # TODO: delete upon PR to StaPH-B
      image_name: "swga:0.4.4"
