# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.

name: Deploy XMFA to FastA image

on: workflow_dispatch

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "."
      dockerfile_name: "./xmfa_to_fasta/2.0/Dockerfile"
      cache: "xmfa-to-fasta"

  build-to-deploy:
    needs: build-to-test
    uses: ./.github/workflows/build-to-deploy.yml
    with:
      path_to_context: "."
      dockerfile_name: "./xmfa_to_fasta/2.0/Dockerfile"
      cache: "xmfa-to-fasta"
      container_name: "xmfa-to-fasta"
      tag: "2.0"
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  run-singularity:
    needs: build-to-deploy
    uses: ./.github/workflows/run-singularity.yml
    with:
      dockerhub_image: "snads/xmfa-to-fasta:2.0"
