name: Deploy FLASH image

on: workflow_dispatch

env:
  TOOL_NAME: flash
  TOOL_VERSION: "1.2.11"

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      params: ${{ steps.env-vars.outputs.params }}
    steps:
      - id: env-vars
        run: echo "::set-output name=params::$(echo $(jq -n 'env'))"

  build-to-test:
    needs: [params]
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}/${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}"
      cache: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}"

  build-to-deploy:
    needs: [params, build-to-test]
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      quay_username: ${{ secrets.quay_username }}
      quay_robot_token: ${{ secrets.quay_robot_token }}
    with:
      path_to_context: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}/${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}"
      cache: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}"
      container_name: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}"
      tag: ${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}

  run-singularity:
    needs: [params, build-to-deploy]  # test singularity run on newly pushed Docker image
    uses: StaPH-B/docker-builds/.github/workflows/run-singularity.yml@master
    with:
      image_name: "${{ fromJson(needs.params.outputs.params).TOOL_NAME }}:${{ fromJson(needs.params.outputs.params).TOOL_VERSION }}"
