name: Deploy Biopython image

on: workflow_dispatch

jobs:

  # This job calls a workflow to build the image to the 'test' stage
  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "biopython/1.79"
      dockerfile_name: "Dockerfile"
      cache: "biopython"

  # This job calls a workflow to build the image to the 'app' stage and pushes the image to Docker Hub
  build-to-deploy:
    needs: build-to-test
    uses: ./.github/workflows/build-to-deploy.yml
    with:
      path_to_context: "biopython/1.79"
      dockerfile_name: "Dockerfile"
      cache: "biopython"
      container_name: "biopython"
      tag: "1.79"
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # This job calls a workflow to pull the image from Docker Hub and test that it can be run as a Singularity container
  run-singularity:
    needs: build-to-deploy
    uses: ./.github/workflows/run-singularity.yml
    with:
      dockerhub_image: "snads/biopython:1.79"  # TODO: change
