# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.
# TODO: change called workflow and dockerhub references to StaPH-B if accepted in PR

name: Push FLASH image

on: workflow_dispatch

jobs:

  build-to-test:
    uses: SarahNadeau/docker-builds/.github/workflows/build-to-test.yml@sarah-dev  # TODO: change
    with:
      path_to_context: "."
      dockerfile_name: "./flash/1.2.11/Dockerfile"
      cache: "flash"

  build-and-push:
    needs: build-to-test  # this jobs needs to run serially, after testing succeeds
    uses: SarahNadeau/docker-builds/.github/workflows/build-and-push.yml@sarah-dev  # TODO: change
    with:
      path_to_context: "."
      dockerfile_name: "./flash/1.2.11/Dockerfile"
      cache: "flash"
      container_name: "flash"
      tag: 1.2.11
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}  # TODO: change
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # TODO: change

  run-singularity:
    needs: build-and-push  # test singularity run on newly pushed Docker image
    uses: SarahNadeau/docker-builds/.github/workflows/run-singularity.yml@sarah-dev  # TODO: change
    with:
      dockerhub_image: "snads/flash:1.2.11"
