name: Test SPAdes image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "spades/3.15.3/Dockerfile"

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "./spades/3.15.3"
      cache: "spades"
