name: Test FLASH image

on: [workflow_dispatch, pull_request]

jobs:

  # This job calls a workflow to build the image to the 'test' stage 
  build-to-test:
    uses: SarahNadeau/docker-builds/.github/workflows/build-to-test.yml@sarah-dev  # TODO: change to pull the workflow from StaPH-B as soon as it is available there
    with:
      path_to_context: "."
      dockerfile_name: "flash/1.2.11/Dockerfile"
      cache: "flash"
