name: Test FLASH image

on: [workflow_dispatch, pull_request]

jobs:

  # This job calls a workflow to build the image to the 'test' stage 
  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "."
      dockerfile_name: "flash/1.2.11/Dockerfile"
      cache: "flash"
