name: Test SPAdes image

on: [workflow_dispatch, pull_request]

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "."
      dockerfile_name: "./spades/3.15.3/Dockerfile"
      cache: "spades"
