# This caller workflow builds an image to the "test" stage.
# It takes manual input as to which tool and version to test

name: Test image changes

on:
  push:  ### TEMPORARY
  pull_request:

jobs:

  # This job identifes changed Dockerfiles
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Get changed Dockerfiles
        id: set-matrix
        run: |
          CONTEXT_PATHS=""
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ ${changed_file} =~ Dockerfile ]]; then
              CONTEXT_PATHS="$CONTEXT_PATHS $changed_file"
            fi
          done
          echo "::set-output name=matrix::$CONTEXT_PATHS"

  # This job builds the changed Dockerfiles to the test stage        
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"


# echo '::set-output name=value::[\"a\", \"b\", \"c\"]'
          # echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --names)"

    #   - name: Build image(s) to test stage
    #     uses: ./.github/workflows/build-to-test.yml
    #     with:
    #       path_to_context: "./${{ github.event.inputs.tool }}/${{ github.event.inputs.version }}"
    #       cache: "${{ github.event.inputs.tool }}"


# Scratch notes

# - name: Extract branch name
#   shell: bash
#   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#   id: extract_branch

# jobs:
#   build-to-test:
#     uses: ./.github/workflows/build-to-test.yml
#     with:
#       path_to_context: "./${{ github.event.inputs.tool }}/${{ github.event.inputs.version }}"
#       cache: "${{ github.event.inputs.tool }}"

# run-check: 

#     if: "contains(github.event.head_commit.message, '[ci]')" 

#     https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
#     https://github.community/t/can-i-process-only-changed-files-with-github-actions/137814