name: Test Kraken 2 image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "kraken2/2.0.8-beta/Dockerfile"

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "./kraken2/2.0.8-beta"
      cache: "kraken"
