name: Test Kraken image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "kraken/1.0/Dockerfile"

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "./kraken/1.0"
      cache: "kraken"
