name: Test Kraken image

on: [workflow_dispatch, pull_request]

jobs:

  build-to-test:
    uses: SarahNadeau/docker-builds/.github/workflows/build-to-test.yml@sarah-dev  # TODO: change
    with:
      path_to_context: "."
      dockerfile_name: "./kraken/1.0/Dockerfile"
      cache: "kraken"
