name: Test Kraken image

on: [workflow_dispatch, pull_request]

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "."
      dockerfile_name: "./kraken/1.0/Dockerfile"
      cache: "kraken"
